project:
  type: website
  output-dir: docs
  resources: 
    - images/luca.HEIC
    - files/CV_Luca_Danese.pdf

website:
  title: "Luca Danese"
  navbar: false
  search: false
      

format:
  html:
    theme: 
      light: united
      dark:  darkly
    css: styles.css
    toc: true

editor: visual

