project:
  type: website
  output-dir: docs

website:
  title: "Luca Danese"
  navbar: false
  search: false
      

format:
  html:
    theme: 
      light: united
      dark:  darkly
    css: styles.css
    toc: true

editor: visual

